Version 0.7.5   2014-mar-24 -------------  * Upgraded libpng to version 1.6.10-optipng.  * Upgraded zlib to version 1.2.8-optipng.  ! Fixed various build issues with libpng-1.5 and libpng-1.6.    [Fixed by Oliver Schneider]  * Allowed the handling of huge image files (> millions of pixels    per row or column) to be independent of the libpng version.  + Allowed the option -preserve to save the file ownership (UID/GID)    on Unix.    [Requested by Otto Kekäläinen]  ! Fixed a build issue with Clang.  + Added various enhancements to the configure script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10,7 +10,7 @@ man1dir="${man1dir-\$(mandir)/man1}"
 
 cc="${CC-gcc}"
 #cc="${CC-clang}"
-#cc="${CC-c99}"
+#cc="${CC-cc}"
 cflags="$CFLAGS"
 
 enable_debug=0
@@ -20,6 +20,8 @@ with_system_zlib=0
 
 with_preconfigured_libpng=1
 with_preconfigured_zlib=0
+
+unique_file=src/optipng/optipng.c
 
 for arg in "$@"
 do
@@ -58,6 +60,7 @@ do
         echo "Optional features:"
         echo "    -enable-debug           Enable debug build flags and run-time checks"
         echo "Optional packages:"
+        echo "    -with-system-libs       Use all system-supplied libraries (details below)"
         echo "    -with-system-libpng     Use the system-supplied libpng"
         echo "                            [default: false]"
         echo "    -with-system-zlib       Use the system-supplied zlib"
@@ -65,9 +68,12 @@ do
         echo "Environment variables:"
         echo "    CC                      C compiler command"
         echo "    LD                      Linker command"
+        echo "    AR                      Library archiver command"
+        echo "    RANLIB                  Library indexer/randomizer command"
         echo "    CFLAGS                  C compiler flags (e.g. -O3)"
         echo "    CPPFLAGS                C preprocessor flags (e.g. -I DIR)"
         echo "    LDFLAGS                 Linker flags (e.g. -L DIR)"
+        echo "    ARFLAGS                 Library archiver flags (e.g. rcu)"
         echo "    LIBS                    Additional libraries (e.g. -lfoo)"
         exit 0
         ;;
@@ -111,6 +117,14 @@ do
     -disable-debug )
         enable_debug=0
         ;;
+    -with-system-libs )
+        with_system_libpng=1
+        with_system_zlib=1
+        ;;
+    -without-system-libs )
+        with_system_zlib=0
+        with_system_libpng=0
+        ;;
     -with-system-libpng )
         with_system_libpng=1
         # Must use the system-supplied zlib with the system-supplied libpng.
@@ -128,47 +142,24 @@ do
         with_system_libpng=0
         ;;
     * )
-        echo "error: unknown option: $arg"
+        echo "$0: error: unknown option: $arg"
         echo "Type \"$0 -help\" for help"
         exit 64  # EX_USAGE
         ;;
     esac
 done
 
-if test "$with_system_libpng" -ne 0
+if test ! -f "$0"
 then
-    sed_config_libpng="
-        s:@USE_SYSTEM_LIBPNG_TRUE@::g
-        s:@USE_SYSTEM_LIBPNG_FALSE@:#:g
-    "
-else
-    sed_config_libpng="
-        s:@USE_SYSTEM_LIBPNG_FALSE@::g
-        s:@USE_SYSTEM_LIBPNG_TRUE@:#:g
-    "
+    echo "$0: error: cannot find myself; rerun with an absolute file name"
+    exit 1
 fi
 
-if test "$with_system_zlib" -ne 0
+if test ! -r "$unique_file"
 then
-    sed_config_zlib="
-        s:@USE_SYSTEM_ZLIB_TRUE@::g
-        s:@USE_SYSTEM_ZLIB_FALSE@:#:g
-    "
-else
-    sed_config_zlib="
-        s:@USE_SYSTEM_ZLIB_FALSE@::g
-        s:@USE_SYSTEM_ZLIB_TRUE@:#:g
-    "
-    case `uname -s` in
-    mingw* | MINGW* | windows* | WINDOWS* )
-        with_preconfigured_zlib=1
-        sed_config_zlib="
-            $sed_config_zlib
-            s:@ZLIB_MK@:win32/Makefile.gcc:g
-            /MAKE.*ZLIB_MK/ s:distclean:clean:
-        "
-        ;;
-    esac
+    echo "$0: error: cannot find: $unique_file"
+    echo "$0: note: building outside the source directory tree is not supported"
+    exit 1
 fi
 
 test=conftest$$
@@ -189,7 +180,7 @@ esac
 
 rm -f $test.c $test.o
 
-if test $gccish -ne 0
+if test "$gccish" -ne 0
 then
     CC="${CC-$cc}"
     CFLAGS="${CFLAGS--O2 -Wall -Wextra}"
@@ -198,40 +189,101 @@ else
     CFLAGS="${CFLAGS--O}"
 fi
 
-if test $enable_debug -ne 0
+if test "$enable_debug" -ne 0
 then
     CPPFLAGS="$CPPFLAGS -DDEBUG -D_DEBUG"
     CFLAGS="$CFLAGS -g"
     LDFLAGS="$LDFLAGS -g"
 fi
 
-if test $with_system_libpng -eq 0
+if test "$with_system_libpng" -eq 0
 then
+    USE_SYSTEM_LIBPNG_TRUE="#"
+    USE_SYSTEM_LIBPNG_FALSE=""
     if test "$with_preconfigured_libpng" -ne 0
     then
         echo "Using pre-configured libpng..."
-        if test $gccish -ne 0
+        libpng_makefile=scripts/makefile.gcc
+        if test ! -f src/libpng/$libpng_makefile
         then
-            sed_config_libpng="
-                $sed_config_libpng
-                s:@LIBPNG_MK@:scripts/makefile.gcc:g
-            "
-        else
-            sed_config_libpng="
-                $sed_config_libpng
-                s:@LIBPNG_MK@:scripts/makefile.std:g
+            echo "$0: warning: cannot find: src/libpng/$libpng_makefile"
+            with_preconfigured_libpng=0
+        fi
+    fi
+    if test "$with_preconfigured_libpng" -ne 0
+    then
+        sed_preconfig_libpng=""
+        if test "$CC"
+        then
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^CC *=.*|CC = $CC|
             "
         fi
+        if test "$CFLAGS"
+        then
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^CFLAGS *=.*|CFLAGS = $CFLAGS|
+            "
+        fi
+        if test "$CPPFLAGS"
+        then
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^CPPFLAGS *=.*|CPPFLAGS = $CPPFLAGS|
+            "
+        fi
+        if test "$LD"
+        then
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^LD *=.*|LD = $LD|
+            "
+        fi
+        if test "$LDFLAGS"
+        then
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^LDFLAGS *=.*|LDFLAGS = $LDFLAGS|
+            "
+        fi
+        if test "$AR$ARFLAGS"
+        then
+            AR="${AR-ar}"
+            ARFLAGS="${ARFLAGS-cru}"
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^AR *=.*|AR = $AR|
+                s|^ARFLAGS *=.*|ARFLAGS = $ARFLAGS|
+                s|^AR_\([A-Z]*\) *=.*|AR_\1 = $AR $ARFLAGS|
+            "
+        fi
+        if test "$RANLIB"
+        then
+            sed_preconfig_libpng="
+                $sed_preconfig_libpng
+                s|^RANLIB *=.*|RANLIB = $RANLIB|
+            "
+        fi
+        sed "$sed_preconfig_libpng" \
+            src/libpng/$libpng_makefile > src/libpng/Makefile
+        LIBPNG_MK=Makefile
+        # The pre-configured makefiles in libpng don't do distclean.
+        LIBPNG_DISTCLEAN="clean"
+        LIBPNG_DISTCLEAN_XCMD="\$(RM_F) \$(LIBPNG_MK)"
     else
         echo "Configuring libpng..."
         (cd src/libpng && ./configure)
         if test $? -ne 0
         then
-            echo "error: could not configure: libpng"
+            echo "$0: error: could not configure: libpng"
             exit 1
         fi
     fi
 else
+    USE_SYSTEM_LIBPNG_TRUE=""
+    USE_SYSTEM_LIBPNG_FALSE="#"
     echo "Checking for system libpng..."
     test=conftest$$
 cat > $test.c <<EOM
@@ -246,27 +298,65 @@ EOM
     rm -f $test.c $test.o
     if test $status -ne 0
     then
-        echo "error: missing libpng or incorrect libpng version"
-        echo "note: libpng version 1.2.9 or higher is required"
+        echo "$0: error: missing libpng or incorrect libpng version"
+        echo "$0: note: libpng version 1.2.9 or higher is required"
         exit 1
     fi
 fi
 
-if test $with_system_zlib -eq 0
+ZLIB_MK=Makefile
+ZLIB_DISTCLEAN=distclean
+if test "$with_system_zlib" -ne 0
 then
+    USE_SYSTEM_ZLIB_TRUE=""
+    USE_SYSTEM_ZLIB_FALSE="#"
+else
+    USE_SYSTEM_ZLIB_TRUE="#"
+    USE_SYSTEM_ZLIB_FALSE=""
+    case `(uname -s) 2>/dev/null || echo unknown` in
+    mingw* | MINGW* | windows* | WINDOWS* )
+        with_preconfigured_zlib=1
+        ZLIB_MK=win32/Makefile.gcc
+        ZLIB_DISTCLEAN=clean
+        ;;
+    esac
+fi
+
+if test "$with_system_zlib" -eq 0
+then
+    USE_SYSTEM_ZLIB_TRUE="#"
+    USE_SYSTEM_ZLIB_FALSE=""
+    case `(uname -s) 2>/dev/null || echo unknown` in
+    mingw* | MINGW* | windows* | WINDOWS* )
+        # zlib configure is known to fail on MinGW.
+        zlib_makefile=win32/Makefile.gcc
+        if test -f src/zlib/$zlib_makefile
+        then
+            with_preconfigured_zlib=1
+        else
+            echo "$0: warning: cannot find: src/zlib/$zlib_makefile"
+            with_preconfigured_zlib=0
+        fi
+        ;;
+    esac
     if test "$with_preconfigured_zlib" -ne 0
     then
         echo "Using pre-configured zlib..."
+        ZLIB_MK="$zlib_makefile"
+        # The pre-configured makefiles in zlib don't do distclean.
+        ZLIB_DISTCLEAN=clean
     else
         echo "Configuring zlib..."
         (cd src/zlib && ./configure --static)
         if test $? -ne 0
         then
-            echo "error: could not configure: zlib"
+            echo "$0: error: could not configure: zlib"
             exit 1
         fi
     fi
 else
+    USE_SYSTEM_ZLIB_TRUE=""
+    USE_SYSTEM_ZLIB_FALSE="#"
     echo "Checking for system zlib..."
     test=conftest$$
 cat > $test.c <<EOM
@@ -281,37 +371,45 @@ EOM
     rm -f $test.c $test.o
     if test $status -ne 0
     then
-        echo "error: missing zlib or incorrect zlib version"
-        echo "note: zlib version 1.2.1 or higher is required"
+        echo "$0: error: missing zlib or incorrect zlib version"
+        echo "$0: note: zlib version 1.2.1 or higher is required"
         exit 1
     fi
 fi
 
 sed_config="
-    $sed_config_libpng
-    $sed_config_zlib
-    s#@prefix@#$prefix#g
-    s#@exec_prefix@#$exec_prefix#g
-    s#@bindir@#$bindir#g
-    s#@mandir@#$mandir#g
-    s#@man1dir@#$man1dir#g
-    s#@CC@#${CC-cc}#g
-    s#@CFLAGS@#${CFLAGS--O}#g
-    s#@CPP@#${CPP-\$(CC) -E}#g
-    s#@CPPFLAGS@#${CPPFLAGS-}#g
-    s#@LD@#${LD-\$(CC)}#g
-    s#@LDFLAGS@#${LDFLAGS--s}#g
-    s#@AR@#${AR-ar}#g
-    s#@ARFLAGS@#${ARFLAGS-cru}#g
-    s#@RANLIB@#${RANLIB-ranlib}#g
-    s#@LIBS@#${LIBS-}#g
-    s#@LIBM@#${LIBM--lm}#g
-    s#@LIBZ@#${LIBZ--lz}#g
-    s#@LIBPNG@#${LIBPNG--lpng}#g
-    s#@DIFF@#${DIFF-diff -b -u}#g
-    s#@RM_F@#${RM_F-rm -f}#g
-    s#@[A-Z]*_MK@#Makefile#g
-    s# *\$##
+    s|@prefix@|$prefix|g
+    s|@exec_prefix@|$exec_prefix|g
+    s|@bindir@|$bindir|g
+    s|@mandir@|$mandir|g
+    s|@man1dir@|$man1dir|g
+    s|@USE_SYSTEM_LIBPNG_TRUE@|$USE_SYSTEM_LIBPNG_TRUE|g
+    s|@USE_SYSTEM_LIBPNG_FALSE@|$USE_SYSTEM_LIBPNG_FALSE|g
+    s|@USE_SYSTEM_ZLIB_TRUE@|$USE_SYSTEM_ZLIB_TRUE|g
+    s|@USE_SYSTEM_ZLIB_FALSE@|$USE_SYSTEM_ZLIB_FALSE|g
+    s|@CC@|${CC-cc}|g
+    s|@CFLAGS@|${CFLAGS--O}|g
+    s|@CPP@|${CPP-\$(CC) -E}|g
+    s|@CPPFLAGS@|${CPPFLAGS-}|g
+    s|@LD@|${LD-\$(CC)}|g
+    s|@LDFLAGS@|${LDFLAGS--s}|g
+    s|@AR@|${AR-ar}|g
+    s|@ARFLAGS@|${ARFLAGS-cru}|g
+    s|@RANLIB@|${RANLIB-ranlib}|g
+    s|@LIBS@|${LIBS-}|g
+    s|@LIBM@|${LIBM--lm}|g
+    s|@LIBZ@|${LIBZ--lz}|g
+    s|@LIBPNG@|${LIBPNG--lpng}|g
+    s|@DIFF@|${DIFF-diff -b -u}|g
+    s|@RM_F@|${RM_F-rm -f}|g
+    s|@LIBPNG_MK@|${LIBPNG_MK-Makefile}|g
+    s|@LIBPNG_MK_DEF@|${LIBPNG_MK_DEF-PNGLIBCONF_H_PREBUILT=pnglibconf.h.optipng}|g
+    s|@LIBPNG_DISTCLEAN@|${LIBPNG_DISTCLEAN-distclean}|g
+    s|@LIBPNG_DISTCLEAN_XCMD@|${LIBPNG_DISTCLEAN_XCMD-true}|g
+    s|@ZLIB_MK@|${ZLIB_MK-Makefile}|g
+    s|@ZLIB_DISTCLEAN@|${ZLIB_DISTCLEAN-distclean}|g
+    s|@[A-Z]*_MK@|Makefile|g
+    s| *\$||
 "
 
 for makefile in \
